worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  gzip on;
  gzip_vary on;
  gzip_min_length 256;
  gzip_proxied any;
  gzip_types
    text/plain
    text/css
    text/javascript
    application/javascript
    application/x-javascript
    application/xml
    application/json
    application/ld+json
    image/svg+xml
    application/wasm;

  server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/security-headers.conf;

    location / {
      try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css)$ {
      expires 1y;
      add_header Cache-Control "public, immutable";
      include /etc/nginx/security-headers.conf;
      access_log off;
    }

    location ~* \.(?:woff2?|svg|ico|png|jpg|jpeg|gif|webp|wasm)$ {
      expires 7d;
      add_header Cache-Control "public";
      include /etc/nginx/security-headers.conf;
      access_log off;
    }
  }
}
